import { Dimensions, StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    paddingHorizontal: 20,
    marginTop: 20,
  },
  passwordContainer: {
    paddingVertical: 13,
    paddingHorizontal: 20,
    backgroundColor: "#EDEEF1",
    borderRadius: 10,
    marginBottom: 5,
    marginVertical: 5,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  passwordInput: {
    fontSize: 16,
    flexBasis: "90%",
  },
  input: {
    paddingVertical: 13,
    paddingHorizontal: 20,
    backgroundColor: "#EDEEF1",
    borderRadius: 10,
    marginBottom: 5,
    fontSize: 16,
    marginVertical: 5,
  },
  login: {
    marginVertical: 20,
    textAlign: "center",
    backgroundColor: "#139E97",
    fontSize: 18,
    borderRadius: 15,
    paddingVertical: 13,
    color: "white",
  },
  loading: {
    marginVertical: 30,
    paddingVertical: 13,
  },
  infoContainer: {
    textAlign: "center",
  },
  title: {
    color: "#777879",
    fontSize: 25,
    fontWeight: "bold",
    marginBottom: 15,
  },
  socials: {
    alignItems: "center",
    paddingHorizontal: 15,
    marginBottom: 30,
  },
  socialContainer: {
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#EDEEF1",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 15,
  },
  socialText: {
    paddingHorizontal: 20,
    fontWeight: "bold",
  },
  circleRight: {
    backgroundColor: "#139E97",
    opacity: 0.5,
    width: 200,
    height: 200,
    borderRadius: 100,
    position: "absolute",
    bottom: "-15%",
    left: -120,
  },
  circleLeft: {
    backgroundColor: "#139E97",
    position: "absolute",
    opacity: 0.3,
    width: 400,
    height: 400,
    borderRadius: 200,
    bottom: "9%",
    right: "-70%",
  },
  logo: {
    alignItems: "center",
  },
});
